Fix

diff --git a/.github/workflows/update_images.yaml b/.github/workflows/update_images.yaml
--- a/.github/workflows/update_images.yaml
+++ b/.github/workflows/update_images.yaml
@@ -18,6 +18,7 @@ jobs:
             repo: influxdata/telegraf
             suffix: "alpine"
 
+
     steps:
       - name: Check out
         uses: actions/checkout@v3
@@ -40,20 +41,22 @@ jobs:
           echo "version=$version" >> $GITHUB_OUTPUT
 
       - name: Check if image is already built
+        id: exists
+        continue-on-error: true # We need to handle exit status
         env:
           TAG: "${{ steps.last_version.outputs.version }}-${{ matrix.image.suffix }}"
         run: |
           docker manifest inspect ghcr.io/${{ github.repository_owner }}/${{ matrix.image.name }}:${{ env.TAG }}
+          echo "code=$?" >> $GITHUB_OUTPUT
 
-      # TODO: check if tag already exists
-
-      # - name: Build and publish a Docker image for ${{ github.repository }}
-      #   uses: macbre/push-to-ghcr@master
-      #   env:
-      #     TAG: "${{ steps.last_version.outputs.version }}-${{ matrix.image.suffix }}"
-      #   with:
-      #     image_name: ${{ github.repository_owner }}/${{ matrix.image.name }}
-      #     github_token: ${{ secrets.GITHUB_TOKEN }}
-      #     dockerfile: "${{ matrix.image.name }}/Dockerfile"
-      #     image_tag: "${{ env.TAG }}"
-      #     context: "--build-arg VERSION=${{ env.TAG }} ${{ matrix.image.name }}/Dockerfile"
+      - name: Build and publish a Docker image for ${{ github.repository }}
+        if: ${{ steps.exists.outputs.code != 0 }}
+        uses: macbre/push-to-ghcr@master
+        env:
+          TAG: "${{ steps.last_version.outputs.version }}-${{ matrix.image.suffix }}"
+        with:
+          image_name: ${{ github.repository_owner }}/${{ matrix.image.name }}
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          dockerfile: "${{ matrix.image.name }}/Dockerfile"
+          image_tag: "${{ env.TAG }}"
+          context: "--build-arg VERSION=${{ env.TAG }} ${{ matrix.image.name }}/Dockerfile"
